Repository ElementsProject/cln-application, pull requests merged in 2024-03, with the labels that each got.

#41 Add react router
  .gitignore
  apps/frontend/package.json
  apps/frontend/src/components/App/App.scss
  apps/frontend/src/components/App/App.test.tsx
  apps/frontend/src/components/App/App.tsx
  apps/frontend/src/components/bookkeeper/BkprRoot/BkprRoot.scss
  apps/frontend/src/components/bookkeeper/BkprRoot/BkprRoot.test.tsx
  apps/frontend/src/components/bookkeeper/BkprRoot/BkprRoot.tsx
  apps/frontend/src/components/cln/CLNHome/CLNHome.scss
  apps/frontend/src/components/cln/CLNHome/CLNHome.test.tsx
  apps/frontend/src/components/cln/CLNHome/CLNHome.tsx
  apps/frontend/src/utilities/test-utilities.tsx
  env.sh
  package-lock.json
Labels: enhancement

#42 Fix empty transactions channel helper text
  apps/frontend/src/components/cln/CLNTransactionsList/CLNTransactionsList.test.tsx
  apps/frontend/src/components/cln/CLNTransactionsList/CLNTransactionsList.tsx
Labels: bug

#47 Update to listpeerchannels
  apps/backend/dist/controllers/lightning.js
  apps/backend/source/controllers/lightning.ts
  apps/backend/source/models/lightning.ts
  apps/frontend/src/components/cln/CLNTransactionsList/CLNTransactionsList.test.tsx
  apps/frontend/src/components/cln/CLNTransactionsList/CLNTransactionsList.tsx
  apps/frontend/src/components/cln/ChannelDetails/ChannelDetails.tsx
  apps/frontend/src/components/cln/Channels/Channels.test.tsx
  apps/frontend/src/components/cln/Channels/Channels.tsx
  apps/frontend/src/components/cln/ChannelsCard/ChannelsCard.tsx
  apps/frontend/src/components/cln/Overview/Overview.test.tsx
  apps/frontend/src/components/cln/Overview/Overview.tsx
  apps/frontend/src/hooks/use-http.ts
  apps/frontend/src/store/AppContext.tsx
  apps/frontend/src/types/app-context.type.ts
  apps/frontend/src/types/lightning-wallet.type.ts
  apps/frontend/src/utilities/constants.ts
  apps/frontend/src/utilities/data-formatters.ts
  apps/frontend/src/utilities/test-utilities.tsx
Labels: version compatibility

#49 Updated the mock data and checks with more realistic dataset
  apps/frontend/src/components/cln/BTCTransaction/BTCTransaction.test.tsx
  apps/frontend/src/components/cln/BTCWallet/BTCWallet.test.tsx
  apps/frontend/src/components/cln/CLNOffer/CLNOffer.test.tsx
  apps/frontend/src/components/cln/CLNOffersList/CLNOffersList.test.tsx
  apps/frontend/src/components/cln/CLNTransaction/CLNTransaction.test.tsx
  apps/frontend/src/components/cln/CLNTransactionsList/CLNTransactionsList.test.tsx
  apps/frontend/src/components/cln/CLNWallet/CLNWallet.test.tsx
  apps/frontend/src/components/cln/Channels/Channels.test.tsx
  apps/frontend/src/components/cln/Overview/Overview.test.tsx
  apps/frontend/src/types/lightning-wallet.type.ts
  apps/frontend/src/utilities/test-utilities.tsx
Labels: enhancement, tests

#50 Remove msatoshi_received, msatoshi, msatoshi_sent from Payments and I…
  apps/frontend/src/components/cln/CLNSend/CLNSend.tsx
  apps/frontend/src/components/cln/CLNTransaction/CLNTransaction.tsx
  apps/frontend/src/components/cln/CLNTransactionsList/CLNTransactionsList.tsx
  apps/frontend/src/store/AppContext.tsx
  apps/frontend/src/types/lightning-wallet.type.ts
  apps/frontend/src/utilities/test-utilities.tsx
Labels: version compatibility

#51 RC version compatibility check
  apps/frontend/src/hooks/use-http.ts
  apps/frontend/src/utilities/data-formatters.test.tsx
  apps/frontend/src/utilities/data-formatters.ts
Labels: bug
